[program:the-space-management-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/the-space-management/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/the-space-management/storage/logs/worker.log
stopwaitsecs=3600

[program:the-space-management-shadow-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/the-space-management/artisan queue:work redis --queue=shadow --sleep=3 --tries=1 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/the-space-management/storage/logs/shadow-worker.log
stopwaitsecs=3600
